#!/bin/sh
#

# Copyright (C) 2013 THE isodumper'S COPYRIGHT HOLDER
# This file is distributed under the same license as the isodumper package.

# Author isodumper software= papoteur <papoteur@mageialinux-online.org>
# Author binary file= Geiger David <david.david@mageialinux-online.org>

set -e

TERM=xterm

DIR=/usr/lib/isodumper

$DIR/isodumper.py $1
